# Generated by Django 5.1.4 on 2024-12-20 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamics', '0013_remove_chatmessage_request_remove_message_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='aceptado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aceptadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
